apiVersion: v1
kind: ServiceAccount
metadata:
  name: source-code-to-url
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: source-code-to-url
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  - revisions
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: source-code-to-url
subjects:
- kind: ServiceAccount
  name: source-code-to-url
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: source-code-to-url
