apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push
  labels:
    source: github-webhook
spec:
  interceptors:
  - name: "Only trigger by repo: wei840222/pingu-line-bot"
    ref:
      name: cel
    params:
    - name: filter
      value: body.repository.full_name == 'wei840222/pingu-line-bot'
  - name: Only trigger by push event
    ref:
      name: github
    params:
    - name: eventTypes
      value:
      - push
  bindings:
  - name: source-code-url
    value: $(body.repository.clone_url)
  - name: commit-sha
    value: $(body.head_commit.id)
  - name: image-registry-url
    value: $(body.repository.full_name)
  template:
    spec:
      params:
      - name: source-code-url
      - name: commit-sha
      - name: image-registry-url
      resourcetemplates:
      - apiVersion: tekton.dev/v1beta1
        kind: PipelineRun
        metadata:
          generateName: source-code-to-url-
        spec:
          serviceAccountName: source-code-to-url
          pipelineRef:
            name: source-code-to-url
          params:
          - name: source-code-url
            value: $(tt.params.source-code-url)
          - name: commit-sha
            value: $(tt.params.commit-sha)
          - name: image-registry-url
            value: $(tt.params.image-registry-url)
          - name: application-namespace
            value: pingu
          - name: application-name
            value: line-bot
          workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: registry-credentials
            secret:
              secretName: docker-credentials
          - name: application-env-credentials
            secret:
              secretName: env
