apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pingu
configurations:
- ./configurations/tekton-namereferences.yaml
resources:
- ./resources/pipeline.yaml
- ./resources/rbac.yaml
- ./resources/trigger.yaml
secretGenerator:
- name: docker-credentials
  type: Opaque
  files:
  - config.json=./configs/docker.json
- name: env
  type: Opaque
  files:
  - env.txt=./configs/env.txt
